name: Deploy with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install myapp ./mychart \
            --namespace production \
            --create-namespace \
            -f ./mychart/values-prod.yaml
