name: Deploy Nginx with Helm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Nginx Image
        run: |
          docker pull nginx:latest

      - name: Import Nginx Image into K3s
        run: |
          docker save nginx:latest | sudo k3s ctr images import -

      - name: Deploy with Helm
        run: |
          helm upgrade --install nginx-app ./mychart

      - name: Verify Deployment
        run: |
          helm status nginx-app
          kubectl get pods
          kubectl get svc
